import { supabase } from '../supabase';
import type { BankStatementRow } from '../bankStatement';

type Json = Record<string, unknown>;
const rpcClient = supabase as unknown as { rpc: (name: string, args?: Record<string, unknown>) => Promise<{ data: unknown; error: { message: string } | null }> };
const text=(v:unknown)=>String(v??'');const nullable=(v:unknown):string|null=>v==null||v===''?null:String(v);const num=(v:unknown)=>Number(v)||0;
async function rpc<T>(name:string,args?:Record<string,unknown>):Promise<T>{const {data,error}=await rpcClient.rpc(name,args);if(error)throw new Error(error.message);return data as T;}
export type FinanceAccountRef={id:string;nome:string;tipo:string;saldo_inicial:number;data_saldo_inicial:string|null};
export type BankImport={import_id:string;account_id:string;file_name:string;format:string;period_start:string|null;period_end:string|null;status:string;created_at:string;lines:number;pending:number;matched:number;ignored:number;pending_amount:number;matched_amount:number};
export type BankLine={id:string;import_id:string;line_no:number;external_id:string|null;transaction_date:string;description:string;amount:number;balance:number|null;document_number:string|null;status:string;matched_entry_id:string|null;matched_amount:number|null;match_score:number|null;matched_at:string|null};
export type MatchSuggestion={line_id:string;entry_id:string;descricao:string;data_vencimento:string|null;valor:number;valor_liquidado:number;status:string;score:number};
export type OpenFinanceEntry={id:string;tipo:'receita'|'despesa';descricao:string;data_vencimento:string|null;valor:number;valor_liquidado:number;open_amount:number;client_id:string|null;work_id:string|null};
export type BankReconciliationSnapshot={accounts:FinanceAccountRef[];imports:BankImport[];lines:BankLine[];open_entries:OpenFinanceEntry[];kpis:{pending:number;matched:number;pending_amount:number}};
export async function getBankReconciliationSnapshot(importId?:string):Promise<BankReconciliationSnapshot>{const raw=await rpc<Json>('bank_reconciliation_snapshot',{p_import_id:importId||null});const k=(raw.kpis??{})as Json;return{
 accounts:((raw.accounts??[])as Json[]).map(r=>({id:text(r.id),nome:text(r.nome),tipo:text(r.tipo),saldo_inicial:num(r.saldo_inicial),data_saldo_inicial:nullable(r.data_saldo_inicial)})),
 imports:((raw.imports??[])as Json[]).map(r=>({import_id:text(r.import_id),account_id:text(r.account_id),file_name:text(r.file_name),format:text(r.format),period_start:nullable(r.period_start),period_end:nullable(r.period_end),status:text(r.status),created_at:text(r.created_at),lines:num(r.lines),pending:num(r.pending),matched:num(r.matched),ignored:num(r.ignored),pending_amount:num(r.pending_amount),matched_amount:num(r.matched_amount)})),
 lines:((raw.lines??[])as Json[]).map(r=>({id:text(r.id),import_id:text(r.import_id),line_no:num(r.line_no),external_id:nullable(r.external_id),transaction_date:text(r.transaction_date),description:text(r.description),amount:num(r.amount),balance:r.balance==null?null:num(r.balance),document_number:nullable(r.document_number),status:text(r.status),matched_entry_id:nullable(r.matched_entry_id),matched_amount:r.matched_amount==null?null:num(r.matched_amount),match_score:r.match_score==null?null:num(r.match_score),matched_at:nullable(r.matched_at)})),
 open_entries:((raw.open_entries??[])as Json[]).map(r=>({id:text(r.id),tipo:text(r.tipo)==='despesa'?'despesa':'receita',descricao:text(r.descricao),data_vencimento:nullable(r.data_vencimento),valor:num(r.valor),valor_liquidado:num(r.valor_liquidado),open_amount:num(r.open_amount),client_id:nullable(r.client_id),work_id:nullable(r.work_id)})),
 kpis:{pending:num(k.pending),matched:num(k.matched),pending_amount:num(k.pending_amount)}};}
export async function importBankStatement(accountId:string,fileName:string,fileHash:string,format:'ofx'|'csv',rows:BankStatementRow[]):Promise<string>{return String(await rpc('import_bank_statement',{p_account_id:accountId,p_file_name:fileName,p_file_hash:fileHash,p_format:format,p_rows:rows,p_metadata:{parser:'frontend-v223'}}));}
export async function suggestBankMatches(importId:string):Promise<MatchSuggestion[]>{const rows=await rpc<Json[]>('suggest_bank_matches',{p_import_id:importId});return(rows??[]).map(r=>({line_id:text(r.line_id),entry_id:text(r.entry_id),descricao:text(r.descricao),data_vencimento:nullable(r.data_vencimento),valor:num(r.valor),valor_liquidado:num(r.valor_liquidado),status:text(r.status),score:num(r.score)}));}
export async function reconcileBankLine(lineId:string,entryId?:string,action:'conciliar'|'ignorar'|'reabrir'='conciliar'):Promise<Json>{return rpc('reconcile_bank_line',{p_line_id:lineId,p_entry_id:entryId||null,p_action:action});}
