import { supabase } from '../supabase';
const db = supabase as unknown as { rpc: (name: string, args?: Record<string, unknown>) => Promise<{ data: unknown; error: { message: string } | null }> };
export type BroadcastRow = { id: string; titulo: string; corpo: string; tipo: string; canal: string; requer_ciencia: boolean; total_recipients: number; delivered_count: number; acked_count: number; pending_count: number; created_at: string; work_nome: string | null; client_nome: string | null; filter_role: string | null; email_enqueued: number };
export type MyBroadcast = { broadcast_id: string; titulo: string; corpo: string; tipo: string; canal: string; requer_ciencia: boolean; delivered_at: string; acknowledged_at: string | null; sender_name: string | null };
export type AckReport = { total_recipients: number; acked: number; pending: number; recipients: Array<{ member_id: string; name: string; email: string; role: string; acknowledged_at: string | null }> };
const rec = (v: unknown) => (v && typeof v === 'object' ? v as Record<string, unknown> : {});
const num = (v: unknown) => Number(v ?? 0) || 0;
const txt = (v: unknown) => String(v ?? '');
const nul = (v: unknown) => v == null ? null : String(v);
const hist = (v: unknown): BroadcastRow => { const r=rec(v); return { id:txt(r.id), titulo:txt(r.titulo), corpo:txt(r.corpo), tipo:txt(r.tipo), canal:txt(r.canal), requer_ciencia:r.requer_ciencia===true, total_recipients:num(r.total_recipients), delivered_count:num(r.delivered_count), acked_count:num(r.acked_count), pending_count:num(r.pending_count), created_at:txt(r.created_at), work_nome:nul(r.work_nome), client_nome:nul(r.client_nome), filter_role:nul(r.filter_role), email_enqueued:num(r.email_enqueued) }; };
const mine = (v: unknown): MyBroadcast => { const r=rec(v); return { broadcast_id:txt(r.broadcast_id), titulo:txt(r.titulo), corpo:txt(r.corpo), tipo:txt(r.tipo), canal:txt(r.canal), requer_ciencia:r.requer_ciencia===true, delivered_at:txt(r.delivered_at), acknowledged_at:nul(r.acknowledged_at), sender_name:nul(r.sender_name) }; };
export async function listBroadcasts(limit=100): Promise<BroadcastRow[]> { const {data,error}=await db.rpc('list_broadcasts',{p_limit:limit}); if(error) throw new Error(error.message); return ((data??[]) as unknown[]).map(hist); }
export async function listMyBroadcasts(): Promise<MyBroadcast[]> { const {data,error}=await db.rpc('list_my_broadcasts',{p_pending_only:false,p_limit:100}); if(error) throw new Error(error.message); return ((data??[]) as unknown[]).map(mine); }
export async function previewBroadcast(input:{workId?:string|null; clientId?:string|null; role?:string|null}) { const {data,error}=await db.rpc('preview_broadcast_recipients',{p_filter_work_id:input.workId||null,p_filter_client_id:input.clientId||null,p_filter_role:input.role||null}); if(error) throw new Error(error.message); const r=rec(data); return { total:num(r.total), with_email:num(r.with_email), by_role:rec(r.by_role) as Record<string,number> }; }
export async function sendBroadcast(input:{titulo:string; corpo:string; tipo:string; canal:string; role?:string|null; workId?:string|null; clientId?:string|null; requerCiencia:boolean; actionUrl?:string|null}) { const {data,error}=await db.rpc('send_broadcast',{p_titulo:input.titulo,p_corpo:input.corpo,p_tipo:input.tipo,p_filter_work_id:input.workId||null,p_filter_client_id:input.clientId||null,p_filter_role:input.role||null,p_requer_ciencia:input.requerCiencia,p_canal:input.canal,p_action_url:input.actionUrl||null}); if(error) throw new Error(error.message); const r=rec(data); return { broadcast_id:txt(r.broadcast_id), total_recipients:num(r.total_recipients), email_enqueued:num(r.email_enqueued) }; }
export async function acknowledgeBroadcast(id:string) { const {error}=await db.rpc('acknowledge_broadcast',{p_broadcast_id:id}); if(error) throw new Error(error.message); }
export async function broadcastAckReport(id:string): Promise<AckReport> { const {data,error}=await db.rpc('broadcast_ack_report',{p_broadcast_id:id}); if(error) throw new Error(error.message); const r=rec(data); const recipients=Array.isArray(r.recipients)?r.recipients:[]; return { total_recipients:num(r.total_recipients), acked:num(r.acked), pending:num(r.pending), recipients: recipients.map((x)=>{const y=rec(x); return {member_id:txt(y.member_id), name:txt(y.name), email:txt(y.email), role:txt(y.role), acknowledged_at:nul(y.acknowledged_at)}})}; }
