import { supabase } from '../supabase';
const db = supabase as unknown as { rpc: (name: string, args?: Record<string, unknown>) => Promise<{ data: unknown; error: { message: string } | null }> };
export type WebhookRow={id:string;label:string;kind:string;url:string;events:string[];active:boolean;secret_hint:string|null;has_signing_secret:boolean;pending_count:number;error_count:number;last_called_at:string|null};
export type ApiKeyRow={id:string;name:string;key_prefix:string;scopes:string[];status:string;last_used_at:string|null};
export type QueueRow={id:string;webhook_label:string;event_type:string;status:string;attempts:number;next_attempt_at:string;last_error:string|null};
const rec=(v:unknown)=>(v&&typeof v==='object'?v as Record<string,unknown>:{}); const str=(v:unknown)=>String(v??''); const nul=(v:unknown)=>v==null?null:String(v); const num=(v:unknown)=>Number(v??0)||0; const arr=(v:unknown)=>Array.isArray(v)?v.map(String):[];
const wh=(v:unknown):WebhookRow=>{const r=rec(v);return{id:str(r.id),label:str(r.label),kind:str(r.kind),url:str(r.url),events:arr(r.events),active:r.active===true,secret_hint:nul(r.secret_hint),has_signing_secret:r.has_signing_secret===true,pending_count:num(r.pending_count),error_count:num(r.error_count),last_called_at:nul(r.last_called_at)}};
const key=(v:unknown):ApiKeyRow=>{const r=rec(v);return{id:str(r.id),name:str(r.name),key_prefix:str(r.key_prefix),scopes:arr(r.scopes),status:str(r.status),last_used_at:nul(r.last_used_at)}};
const q=(v:unknown):QueueRow=>{const r=rec(v);return{id:str(r.id),webhook_label:str(r.webhook_label),event_type:str(r.event_type),status:str(r.status),attempts:num(r.attempts),next_attempt_at:str(r.next_attempt_at),last_error:nul(r.last_error)}};
export async function listTenantWebhooks(){const {data,error}=await db.rpc('list_tenant_webhooks',{}); if(error) throw new Error(error.message); return ((data??[]) as unknown[]).map(wh);}
export async function upsertTenantWebhook(i:{id?:string|null;label:string;kind:string;url:string;events:string[];active:boolean;payloadTemplate?:string|null}){const {data,error}=await db.rpc('upsert_tenant_webhook',{p_id:i.id||null,p_label:i.label,p_kind:i.kind,p_url:i.url,p_events:i.events,p_active:i.active,p_payload_template:i.payloadTemplate||null}); if(error) throw new Error(error.message); return String(data??'');}
export async function rotateWebhookSecret(id:string){const {data,error}=await db.rpc('rotate_webhook_secret',{p_id:id}); if(error) throw new Error(error.message); const r=rec(data); return {secret:str(r.secret),hint:str(r.hint)};}
export async function listApiKeys(){const {data,error}=await db.rpc('list_api_keys',{}); if(error) throw new Error(error.message); return ((data??[]) as unknown[]).map(key);}
export async function createApiKey(name:string,scopes:string[]){const {data,error}=await db.rpc('create_api_key',{p_name:name,p_scopes:scopes,p_expires_at:null}); if(error) throw new Error(error.message); const r=rec(data); return {full_key:str(r.full_key)};}
export async function revokeApiKey(id:string){const {error}=await db.rpc('revoke_api_key',{p_id:id}); if(error) throw new Error(error.message);}
export async function listWebhookQueueEvents(status?:string){const {data,error}=await db.rpc('list_webhook_queue_events',{p_status:status||null,p_limit:100}); if(error) throw new Error(error.message); return ((data??[]) as unknown[]).map(q);}
