import { useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Button } from '../../components/ui/Button';
import { Card, CardHeader } from '../../components/ui/Card';
import { FilePicker } from '../../components/ui/FilePicker';
import { SelectField } from '../../components/ui/Field';
import { Modal } from '../../components/ui/Modal';
import { PageHeader } from '../../components/ui/PageHeader';
import { EmptyState, ErrorState, LoadingState } from '../../components/ui/State';
import { Stat } from '../../components/ui/Stat';
import { useAuth } from '../../lib/auth';
import { getBankReconciliationSnapshot, importBankStatement, reconcileBankLine, suggestBankMatches, type BankLine, type MatchSuggestion } from '../../lib/api/bankReconciliation';
import { parseBankStatement, sha256Text } from '../../lib/bankStatement';
import { useToast } from '../../lib/toast';
import { dateBr, money, Pill, TableShell, Td, Th } from './product/ProductUi';

type StatusFilter = 'todos' | 'pendente' | 'conciliado' | 'ignorado';
function tone(status: string) { return status === 'conciliado' ? 'good' as const : status === 'ignorado' ? 'neutral' as const : 'warn' as const; }

export function BankReconciliationPage() {
  const { member, can } = useAuth(); const toast = useToast(); const qc = useQueryClient();
  const [importId, setImportId] = useState(''); const [accountId, setAccountId] = useState(''); const [filter, setFilter] = useState<StatusFilter>('pendente'); const [selectedLine, setSelectedLine] = useState<BankLine | null>(null); const [suggestions, setSuggestions] = useState<MatchSuggestion[]>([]); const [selectedEntry, setSelectedEntry] = useState(''); const [busy, setBusy] = useState(false);
  const snapshot = useQuery({ queryKey: ['bank-reconciliation', member?.tenant_id, importId], enabled: !!member, queryFn: () => getBankReconciliationSnapshot(importId || undefined) });
  const data = snapshot.data;
  const lines = useMemo(() => (data?.lines ?? []).filter((line) => filter === 'todos' || line.status === filter), [data?.lines, filter]);
  const compatibleEntries = useMemo(() => { if (!selectedLine) return []; const tipo = selectedLine.amount > 0 ? 'receita' : 'despesa'; return (data?.open_entries ?? []).filter((entry) => entry.tipo === tipo); }, [data?.open_entries, selectedLine]);
  const suggestedIds = useMemo(() => new Set(suggestions.map((row) => row.entry_id)), [suggestions]);
  async function refresh() { await qc.invalidateQueries({ queryKey: ['bank-reconciliation'] }); }
  async function upload(file: File) { if (!accountId) return toast('Selecione a conta bancária antes de importar.', 'warning'); setBusy(true); try { const content = await file.text(); const parsed = parseBankStatement(file.name, content); const hash = await sha256Text(content); const id = await importBankStatement(accountId, file.name, hash, parsed.format, parsed.rows); setImportId(id); await refresh(); toast(`${parsed.rows.length} movimento(s) importado(s).`, 'success'); } catch (error) { toast((error as Error).message, 'error'); } finally { setBusy(false); } }
  async function openMatch(line: BankLine) { setSelectedLine(line); setSelectedEntry(line.matched_entry_id ?? ''); if (!line.import_id) return; setBusy(true); try { const rows = await suggestBankMatches(line.import_id); const options = rows.filter((row) => row.line_id === line.id); setSuggestions(options); if (!line.matched_entry_id && (options[0]?.score ?? 0) >= 70) setSelectedEntry(options[0].entry_id); } catch (error) { setSuggestions([]); toast((error as Error).message, 'error'); } finally { setBusy(false); } }
  async function apply(action: 'conciliar' | 'ignorar' | 'reabrir', line = selectedLine) { if (!line) return; if (action === 'conciliar' && !selectedEntry) return toast('Selecione um título financeiro para conciliar.', 'warning'); setBusy(true); try { await reconcileBankLine(line.id, action === 'conciliar' ? selectedEntry : undefined, action); setSelectedLine(null); setSelectedEntry(''); setSuggestions([]); await refresh(); toast(action === 'conciliar' ? 'Movimento conciliado e título baixado.' : action === 'ignorar' ? 'Movimento ignorado.' : 'Movimento reaberto.', 'success'); } catch (error) { toast((error as Error).message, 'error'); } finally { setBusy(false); } }
  return <div className="space-y-6">
    <PageHeader kicker="Financeiro" title="Conciliação bancária" description="Importe OFX ou CSV, receba sugestões por valor e data e confirme a baixa no título financeiro correto." />
    {snapshot.isLoading ? <LoadingState /> : snapshot.error ? <ErrorState message={(snapshot.error as Error).message} /> : <>
      <div className="grid gap-3 md:grid-cols-3"><Stat label="Pendentes" value={data?.kpis.pending ?? 0} /><Stat label="Conciliados" value={data?.kpis.matched ?? 0} /><Stat label="Valor pendente" value={money(data?.kpis.pending_amount ?? 0)} /></div>
      <Card><CardHeader kicker="Importação" title="Novo extrato" /><div className="grid gap-4 p-5 md:grid-cols-[minmax(220px,1fr)_auto]"><SelectField label="Conta financeira" required value={accountId} onChange={(e) => setAccountId(e.target.value)}><option value="">Selecione</option>{(data?.accounts ?? []).map((row) => <option key={row.id} value={row.id}>{row.nome} · {row.tipo}</option>)}</SelectField><div className="flex items-end"><FilePicker accept=".ofx,.csv,text/csv,application/x-ofx" resetAfter disabled={busy || !can('conciliacao.gerenciar')} label={busy ? 'Importando...' : 'Importar OFX/CSV'} onFiles={(files) => { const file = files[0]; if (file) void upload(file); }} /></div></div></Card>
      <Card><CardHeader kicker="Extratos" title="Arquivos importados" /><div className="p-5">{!(data?.imports.length) ? <EmptyState title="Nenhum extrato importado" /> : <TableShell><thead><tr><Th>Arquivo</Th><Th>Período</Th><Th>Linhas</Th><Th>Pendentes</Th><Th>Conciliados</Th><Th>Valor pendente</Th><Th /></tr></thead><tbody>{data!.imports.map((row) => <tr key={row.import_id}><Td><b>{row.file_name}</b><div className="text-xs text-slate-500">{row.format.toUpperCase()}</div></Td><Td>{dateBr(row.period_start)} a {dateBr(row.period_end)}</Td><Td>{row.lines}</Td><Td>{row.pending}</Td><Td>{row.matched}</Td><Td>{money(row.pending_amount)}</Td><Td><Button variant={importId === row.import_id ? 'primary' : 'secondary'} onClick={() => setImportId(row.import_id)}>Abrir</Button></Td></tr>)}</tbody></TableShell>}</div></Card>
      {importId ? <><Card><div className="flex flex-wrap items-end justify-between gap-4 p-5"><SelectField label="Status" value={filter} onChange={(e) => setFilter(e.target.value as StatusFilter)}><option value="todos">Todos</option><option value="pendente">Pendentes</option><option value="conciliado">Conciliados</option><option value="ignorado">Ignorados</option></SelectField><p className="text-sm text-slate-500">{lines.length} movimento(s)</p></div></Card>{!lines.length ? <EmptyState title="Nenhum movimento neste filtro" /> : <TableShell><thead><tr><Th>Data</Th><Th>Descrição</Th><Th>Documento</Th><Th>Valor</Th><Th>Status</Th><Th>Score</Th><Th /></tr></thead><tbody>{lines.map((line) => <tr key={line.id}><Td>{dateBr(line.transaction_date)}</Td><Td><b>{line.description}</b><div className="text-xs text-slate-500">Linha {line.line_no}</div></Td><Td>{line.document_number || '—'}</Td><Td className={line.amount < 0 ? 'text-red-600' : 'text-emerald-700'}>{money(line.amount)}</Td><Td><Pill tone={tone(line.status)}>{line.status}</Pill></Td><Td>{line.match_score == null ? '—' : `${line.match_score}%`}</Td><Td><div className="flex flex-wrap gap-2">{line.status === 'pendente' && can('conciliacao.gerenciar') ? <><Button onClick={() => void openMatch(line)}>Conciliar</Button><Button variant="ghost" onClick={() => void apply('ignorar', line)}>Ignorar</Button></> : null}{line.status !== 'pendente' && can('conciliacao.gerenciar') ? <Button variant="ghost" onClick={() => void apply('reabrir', line)}>Reabrir</Button> : null}</div></Td></tr>)}</tbody></TableShell>}</> : null}
    </>}
    <Modal open={!!selectedLine} title="Conciliar movimento" onClose={() => setSelectedLine(null)} footer={<><Button variant="ghost" onClick={() => setSelectedLine(null)}>Cancelar</Button><Button disabled={busy || !selectedEntry} onClick={() => void apply('conciliar')}>{busy ? 'Conciliando...' : 'Confirmar baixa'}</Button></>}>
      {selectedLine ? <div className="space-y-4"><Card className="p-4"><p className="text-sm font-black text-slate-950 dark:text-white">{selectedLine.description}</p><p className="mt-1 text-sm text-slate-500">{dateBr(selectedLine.transaction_date)} · {money(selectedLine.amount)}</p></Card><SelectField label="Título financeiro" value={selectedEntry} onChange={(e) => setSelectedEntry(e.target.value)}><option value="">Selecione</option>{suggestions.length ? <optgroup label="Sugestões automáticas">{suggestions.map((row) => <option key={row.entry_id} value={row.entry_id}>{Math.round(row.score)}% · {row.descricao} · {dateBr(row.data_vencimento)} · {money(row.valor - row.valor_liquidado)}</option>)}</optgroup> : null}<optgroup label="Demais títulos compatíveis">{compatibleEntries.filter((entry) => !suggestedIds.has(entry.id)).map((entry) => <option key={entry.id} value={entry.id}>{entry.descricao} · {dateBr(entry.data_vencimento)} · {money(entry.open_amount)}</option>)}</optgroup></SelectField>{!busy && !suggestions.length ? <p className="text-sm text-slate-500">Nenhuma sugestão automática encontrada. Selecione manualmente um título aberto compatível.</p> : null}<p className="text-xs text-slate-500">A confirmação registra uma baixa limitada ao saldo aberto. Reabrir desfaz somente o valor desta conciliação.</p></div> : null}
    </Modal>
  </div>;
}
