import { useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Button } from '../../components/ui/Button';
import { Card, CardHeader } from '../../components/ui/Card';
import { Field, SelectField } from '../../components/ui/Field';
import { PageHeader } from '../../components/ui/PageHeader';
import { EmptyState, ErrorState, LoadingState } from '../../components/ui/State';
import { getCapacitySnapshot, listCollaboratorsRef, listEquipmentRef, saveResourceCapacity, saveTeamShift } from '../../lib/api/productEvolution';
import { useToast } from '../../lib/toast';
import { dateBr, MetricCard, number, Pill, TableShell, Td, Th } from './product/ProductUi';

const today = new Date().toISOString().slice(0, 10);
const inDays = (days: number) => { const date = new Date(); date.setDate(date.getDate() + days); return date.toISOString().slice(0, 10); };
export function CapacityPage() {
  const toast = useToast(); const qc = useQueryClient(); const [from, setFrom] = useState(today); const [to, setTo] = useState(inDays(7)); const [busy, setBusy] = useState(false);
  const [shift, setShift] = useState({ colaborador_id: '', data: today, inicio: '08:00', fim: '17:00', tipo: 'disponivel' });
  const [capacity, setCapacity] = useState({ resource_type: 'prensa', equipamento_id: '', colaborador_id: '', data: today, capacidade_unidade: 'cp', capacidade: '0' });
  const snapshot = useQuery({ queryKey: ['product', 'capacity', from, to], queryFn: () => getCapacitySnapshot(from, to) });
  const collaborators = useQuery({ queryKey: ['refs', 'collaborators'], queryFn: listCollaboratorsRef });
  const equipment = useQuery({ queryKey: ['refs', 'equipment'], queryFn: listEquipmentRef });
  const rows = snapshot.data?.rows ?? [];
  const totals = useMemo(() => ({ conflicts: snapshot.data?.conflicts ?? 0, booked: rows.reduce((sum, row) => sum + row.reservado, 0), capacity: rows.reduce((sum, row) => sum + (row.capacidade ?? 0), 0) }), [rows, snapshot.data?.conflicts]);
  async function run(action: () => Promise<unknown>, message: string) { setBusy(true); try { await action(); await qc.invalidateQueries({ queryKey: ['product', 'capacity'] }); toast(message, 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Operação não concluída.', 'error'); } finally { setBusy(false); } }
  return <div className="space-y-6"><PageHeader kicker="Evolução do produto" title="Escala e capacidade" description="Planejamento diário de equipe, prensa, câmara e veículos com detecção de sobrecarga." />
    <Card className="p-4"><div className="grid gap-4 md:grid-cols-3"><Field label="De" type="date" value={from} onChange={(e) => setFrom(e.target.value)} /><Field label="Até" type="date" value={to} onChange={(e) => setTo(e.target.value)} /><div className="flex items-end"><Button variant="secondary" onClick={() => void snapshot.refetch()}>Atualizar</Button></div></div></Card>
    <div className="grid gap-3 md:grid-cols-3"><MetricCard label="Conflitos" value={totals.conflicts} tone={totals.conflicts ? 'bad' : 'good'} /><MetricCard label="Capacidade cadastrada" value={number(totals.capacity, 1)} /><MetricCard label="Carga reservada" value={number(totals.booked, 1)} /></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader kicker="Equipe" title="Registrar jornada" /><div className="grid gap-4 p-5 md:grid-cols-2"><SelectField label="Colaborador" value={shift.colaborador_id} onChange={(e) => setShift({ ...shift, colaborador_id: e.target.value })}><option value="">Selecione</option>{(collaborators.data ?? []).map((row) => <option key={row.id} value={row.id}>{row.label}</option>)}</SelectField><Field label="Data" type="date" value={shift.data} onChange={(e) => setShift({ ...shift, data: e.target.value })} /><Field label="Início" type="time" value={shift.inicio} onChange={(e) => setShift({ ...shift, inicio: e.target.value })} /><Field label="Fim" type="time" value={shift.fim} onChange={(e) => setShift({ ...shift, fim: e.target.value })} /><SelectField label="Situação" value={shift.tipo} onChange={(e) => setShift({ ...shift, tipo: e.target.value })}><option value="disponivel">Disponível</option><option value="folga">Folga</option><option value="ferias">Férias</option><option value="bloqueado">Bloqueado</option></SelectField><div className="flex items-end"><Button disabled={busy || !shift.colaborador_id} onClick={() => void run(() => saveTeamShift(shift), 'Escala salva.')}>Salvar escala</Button></div></div></Card>
      <Card><CardHeader kicker="Recursos" title="Cadastrar capacidade" /><div className="grid gap-4 p-5 md:grid-cols-2"><SelectField label="Tipo" value={capacity.resource_type} onChange={(e) => setCapacity({ ...capacity, resource_type: e.target.value })}>{['prensa','camara','moldador','veiculo'].map((value) => <option key={value}>{value}</option>)}</SelectField><Field label="Data" type="date" value={capacity.data} onChange={(e) => setCapacity({ ...capacity, data: e.target.value })} /><SelectField label="Equipamento" value={capacity.equipamento_id} onChange={(e) => setCapacity({ ...capacity, equipamento_id: e.target.value })}><option value="">Não aplicável</option>{(equipment.data ?? []).map((row) => <option key={row.id} value={row.id}>{row.label}</option>)}</SelectField><SelectField label="Colaborador" value={capacity.colaborador_id} onChange={(e) => setCapacity({ ...capacity, colaborador_id: e.target.value })}><option value="">Não aplicável</option>{(collaborators.data ?? []).map((row) => <option key={row.id} value={row.id}>{row.label}</option>)}</SelectField><Field label="Capacidade" type="number" step="0.1" value={capacity.capacidade} onChange={(e) => setCapacity({ ...capacity, capacidade: e.target.value })} /><Field label="Unidade" value={capacity.capacidade_unidade} onChange={(e) => setCapacity({ ...capacity, capacidade_unidade: e.target.value })} /><div className="md:col-span-2"><Button disabled={busy} onClick={() => void run(() => saveResourceCapacity({ ...capacity, capacidade: Number(capacity.capacidade) }), 'Capacidade salva.')}>Salvar capacidade</Button></div></div></Card></div>
    {snapshot.isLoading ? <LoadingState /> : snapshot.error ? <ErrorState message={(snapshot.error as Error).message} /> : !rows.length ? <EmptyState title="Sem capacidade ou reservas no período" /> : <TableShell><thead><tr><Th>Data</Th><Th>Recurso</Th><Th>Capacidade</Th><Th>Reservado</Th><Th>Utilização</Th></tr></thead><tbody>{rows.map((row, index) => <tr key={`${row.data}-${row.resource_type}-${row.equipamento_id || row.colaborador_id || index}`}><Td>{dateBr(row.data)}</Td><Td><b>{row.equipamento || row.colaborador || row.resource_type}</b><div className="text-xs text-slate-500">{row.resource_type}</div></Td><Td>{row.capacidade == null ? '-' : `${number(row.capacidade, 1)} ${row.capacidade_unidade || ''}`}</Td><Td>{number(row.reservado, 1)} ({row.reservas})</Td><Td><Pill tone={row.conflito ? 'bad' : (row.utilizacao_pct ?? 0) > 85 ? 'warn' : 'good'}>{row.utilizacao_pct == null ? 'sem base' : `${row.utilizacao_pct}%`}</Pill></Td></tr>)}</tbody></TableShell>}
  </div>;
}
