import { useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Button } from '../../components/ui/Button';
import { Card, CardHeader } from '../../components/ui/Card';
import { Field, SelectField, TextArea } from '../../components/ui/Field';
import { PageHeader } from '../../components/ui/PageHeader';
import { EmptyState, ErrorState, LoadingState } from '../../components/ui/State';
import { useToast } from '../../lib/toast';
import { openDeferredTab } from '../../lib/pdf';
import {
  approveContractAddendum, createContractAddendum, generateDocumentPdf, getContractDetail,
  listClientsRef, listContractBalances, listServiceCatalog, listWorksRef, saveContractStructured,
  sendCommercialDocument, type ContractBalance,
} from '../../lib/api/productEvolution';
import { dateBr, MetricCard, money, Pill, TableShell, Td, Th } from './product/ProductUi';

const initial = { id: '', client_id: '', work_id: '', numero: '', descricao: '', vigencia_inicio: '', vigencia_fim: '', limit_amount: '0', payment_terms_days: '30' };
export function ContractsV2Page() {
  const toast = useToast(); const qc = useQueryClient(); const [selected, setSelected] = useState(''); const [form, setForm] = useState(initial); const [busy, setBusy] = useState(false);
  const balances = useQuery({ queryKey: ['product', 'contracts'], queryFn: listContractBalances });
  const clients = useQuery({ queryKey: ['refs', 'clients'], queryFn: listClientsRef });
  const works = useQuery({ queryKey: ['refs', 'works'], queryFn: () => listWorksRef() });
  const catalog = useQuery({ queryKey: ['product', 'catalog', 'active'], queryFn: () => listServiceCatalog(true) });
  const detail = useQuery({ queryKey: ['product', 'contract', selected], queryFn: () => getContractDetail(selected), enabled: Boolean(selected) });
  const rows = balances.data ?? [];
  const totals = useMemo(() => ({ active: rows.filter((row) => row.status === 'ativo').length, limit: rows.reduce((sum, row) => sum + row.valor_limite, 0), measured: rows.reduce((sum, row) => sum + row.valor_medido, 0) }), [rows]);
  const filteredWorks = (works.data ?? []).filter((row) => !form.client_id || row.client_id === form.client_id);

  function edit(row: ContractBalance) { setSelected(row.contract_id); setForm({ id: row.contract_id, client_id: row.client_id, work_id: row.work_id ?? '', numero: row.numero ?? '', descricao: row.descricao ?? '', vigencia_inicio: row.vigencia_inicio ?? '', vigencia_fim: row.vigencia_fim ?? '', limit_amount: String(row.valor_limite), payment_terms_days: '30' }); }
  async function save() { if (!form.client_id) return toast('Selecione o cliente.', 'warning'); setBusy(true); try { await saveContractStructured({ ...form, status: 'ativo', limit_amount: Number(form.limit_amount), valor_contratado: Number(form.limit_amount), payment_terms_days: Number(form.payment_terms_days), price_items: [] }); setForm(initial); await qc.invalidateQueries({ queryKey: ['product', 'contracts'] }); toast('Contrato salvo.', 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Falha ao salvar contrato.', 'error'); } finally { setBusy(false); } }
  async function addCatalogItem(serviceId: string) { if (!selected) return; const service = (catalog.data ?? []).find((row) => row.id === serviceId); if (!service) return; setBusy(true); try { const current = await getContractDetail(selected); const contract = current.contract; await saveContractStructured({ ...contract, id: selected, client_id: contract.client_id, work_id: contract.work_id, price_items: [...current.items, { catalog_item_id: service.id, item_code: service.code, descricao: service.nome, unidade: service.unidade, preco_unitario: service.preco_sugerido, tipo_cobranca: service.tipo_cobranca, regra: service.regra_operacional }] }); await qc.invalidateQueries({ queryKey: ['product', 'contract', selected] }); toast('Serviço incluído.', 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Falha ao incluir item.', 'error'); } finally { setBusy(false); } }
  async function addAddendum() { if (!selected) return; const amount = window.prompt('Valor do aditivo (positivo ou negativo):', '0'); if (amount == null) return; const description = window.prompt('Descrição do aditivo:', 'Ajuste contratual') ?? ''; setBusy(true); try { await createContractAddendum({ contract_id: selected, tipo: 'valor', descricao: description, delta_amount: Number(amount), effective_date: new Date().toISOString().slice(0, 10) }); await qc.invalidateQueries({ queryKey: ['product', 'contract', selected] }); toast('Aditivo criado em rascunho.', 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Falha ao criar aditivo.', 'error'); } finally { setBusy(false); } }
  async function generate() { if (!selected) return; const tab = openDeferredTab('Gerando PDF do contrato…'); setBusy(true); try { const doc = await generateDocumentPdf({ entity_type: 'contrato', entity_id: selected }); tab.openBlob(doc.blob, doc.file_name); toast('Contrato gerado.', 'success'); } catch (error) { tab.fail(); toast(error instanceof Error ? error.message : 'Falha ao gerar documento.', 'error'); } finally { setBusy(false); } }
  async function send() { if (!selected) return; const email = window.prompt('E-mail do destinatário:'); if (!email) return; setBusy(true); try { await sendCommercialDocument('contrato', selected, email); toast('Contrato encaminhado pelo hub de notificações.', 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Falha ao enviar.', 'error'); } finally { setBusy(false); } }

  return <div className="space-y-6"><PageHeader kicker="Evolução do produto" title="Contratos estruturados" description="Escopo, preços, limites, vigência, aditivos, medição e faturamento ligados ao mesmo contrato." />
    <div className="grid gap-3 md:grid-cols-3"><MetricCard label="Contratos ativos" value={totals.active} /><MetricCard label="Valor limite" value={money(totals.limit)} /><MetricCard label="Valor medido" value={money(totals.measured)} /></div>
    <Card><CardHeader kicker="Cadastro" title={form.id ? 'Editar contrato' : 'Novo contrato'} /><div className="space-y-4 p-5"><div className="grid gap-4 md:grid-cols-3"><SelectField label="Cliente" value={form.client_id} onChange={(e) => setForm({ ...form, client_id: e.target.value, work_id: '' })}><option value="">Selecione</option>{(clients.data ?? []).map((row) => <option key={row.id} value={row.id}>{row.label}</option>)}</SelectField><SelectField label="Obra" value={form.work_id} onChange={(e) => setForm({ ...form, work_id: e.target.value })}><option value="">Todas / não definida</option>{filteredWorks.map((row) => <option key={row.id} value={row.id}>{row.label}</option>)}</SelectField><Field label="Número" value={form.numero} onChange={(e) => setForm({ ...form, numero: e.target.value })} /></div><TextArea label="Descrição / escopo" value={form.descricao} onChange={(e) => setForm({ ...form, descricao: e.target.value })} /><div className="grid gap-4 md:grid-cols-4"><Field label="Início" type="date" value={form.vigencia_inicio} onChange={(e) => setForm({ ...form, vigencia_inicio: e.target.value })} /><Field label="Fim" type="date" value={form.vigencia_fim} onChange={(e) => setForm({ ...form, vigencia_fim: e.target.value })} /><Field label="Limite do contrato" type="number" step="0.01" value={form.limit_amount} onChange={(e) => setForm({ ...form, limit_amount: e.target.value })} /><Field label="Prazo de pagamento (dias)" type="number" value={form.payment_terms_days} onChange={(e) => setForm({ ...form, payment_terms_days: e.target.value })} /></div><div className="flex gap-2"><Button disabled={busy} onClick={() => void save()}>Salvar contrato</Button>{form.id ? <Button variant="secondary" onClick={() => setForm(initial)}>Cancelar</Button> : null}</div></div></Card>
    {balances.isLoading ? <LoadingState /> : balances.error ? <ErrorState message={(balances.error as Error).message} /> : !rows.length ? <EmptyState /> : <TableShell><thead><tr><Th>Contrato</Th><Th>Vigência</Th><Th>Limite</Th><Th>Medido</Th><Th>Saldo</Th><Th>Ações</Th></tr></thead><tbody>{rows.map((row) => <tr key={row.contract_id} className={selected === row.contract_id ? 'bg-slate-50 dark:bg-slate-900/40' : ''}><Td><b>{row.numero || 'Sem número'}</b><div className="text-xs text-slate-500">{row.descricao || row.status}</div></Td><Td>{dateBr(row.vigencia_inicio)}–{dateBr(row.vigencia_fim)}</Td><Td>{money(row.valor_limite)}</Td><Td>{money(row.valor_medido)} <span className="text-xs text-slate-500">({row.consumo_pct}%)</span></Td><Td>{money(row.saldo_a_medir)}</Td><Td><Button variant="secondary" onClick={() => edit(row)}>Abrir</Button></Td></tr>)}</tbody></TableShell>}
    {selected ? <Card><CardHeader kicker="Detalhe" title="Escopo e aditivos"><div className="mt-3 flex flex-wrap gap-2"><Button variant="secondary" disabled={busy} onClick={() => void generate()}>Gerar PDF</Button><Button variant="secondary" disabled={busy} onClick={() => void send()}>Enviar</Button><Button variant="secondary" disabled={busy} onClick={() => void addAddendum()}>Novo aditivo</Button></div></CardHeader><div className="space-y-5 p-5">{detail.isLoading ? <LoadingState /> : detail.error ? <ErrorState message={(detail.error as Error).message} /> : <><div><p className="mb-2 text-sm font-bold">Adicionar serviço do catálogo</p><div className="flex flex-wrap gap-2">{(catalog.data ?? []).slice(0, 12).map((service) => <Button key={service.id} variant="secondary" disabled={busy} onClick={() => void addCatalogItem(service.id)}>+ {service.code}</Button>)}</div></div><TableShell><thead><tr><Th>Item</Th><Th>Cobrança</Th><Th>Preço</Th></tr></thead><tbody>{(detail.data?.items ?? []).map((item) => <tr key={item.id}><Td>{item.item_code} · {item.descricao}</Td><Td>{item.tipo_cobranca}</Td><Td>{money(item.preco_unitario)}</Td></tr>)}</tbody></TableShell><div className="space-y-2"><p className="text-sm font-bold">Aditivos</p>{!(detail.data?.addenda.length) ? <EmptyState /> : detail.data?.addenda.map((row) => <div key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div><b>{row.numero} · {row.descricao}</b><div className="text-xs text-slate-500">{dateBr(row.effective_date)} · {money(row.delta_amount)}</div></div><div className="flex items-center gap-2"><Pill tone={row.status === 'aprovado' ? 'good' : 'warn'}>{row.status}</Pill>{row.status === 'rascunho' ? <Button disabled={busy} onClick={async () => { await approveContractAddendum(row.id); await qc.invalidateQueries({ queryKey: ['product', 'contract', selected] }); toast('Aditivo aprovado.', 'success'); }}>Aprovar</Button> : null}</div></div>)}</div></>}</div></Card> : null}
  </div>;
}
