import { useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Button } from '../../components/ui/Button';
import { Card, CardHeader } from '../../components/ui/Card';
import { Field, SelectField, TextArea } from '../../components/ui/Field';
import { Modal } from '../../components/ui/Modal';
import { PageHeader } from '../../components/ui/PageHeader';
import { EmptyState, ErrorState, LoadingState } from '../../components/ui/State';
import { Stat } from '../../components/ui/Stat';
import { useAuth } from '../../lib/auth';
import { convertCrmLeadToProposal, getCrmSnapshot, moveCrmLead, saveCrmActivity, saveCrmLead, type CrmLead } from '../../lib/api/crm';
import { listClientsRef, listWorksRef } from '../../lib/api/productEvolution';
import { useToast } from '../../lib/toast';
import { dateBr, money, Pill } from './product/ProductUi';

type LeadForm = { id?: string; stage_id: string; title: string; company_name: string; contact_name: string; email: string; phone: string; source: string; expected_value: string; probability: string; client_id: string; work_id: string; owner_member_id: string; next_action_at: string };
const emptyLead = (stageId = ''): LeadForm => ({ stage_id: stageId, title: '', company_name: '', contact_name: '', email: '', phone: '', source: '', expected_value: '0', probability: '', client_id: '', work_id: '', owner_member_id: '', next_action_at: '' });
function toLocal(value: string | null) { return value ? value.slice(0, 16) : ''; }

export function CrmPage() {
  const { member, can } = useAuth(); const toast = useToast(); const qc = useQueryClient();
  const [pipelineId, setPipelineId] = useState(''); const [leadForm, setLeadForm] = useState<LeadForm | null>(null); const [activityLead, setActivityLead] = useState<CrmLead | null>(null); const [activity, setActivity] = useState({ activity_type: 'nota', subject: '', detail: '', due_at: '' }); const [busy, setBusy] = useState(false);
  const crm = useQuery({ queryKey: ['crm', member?.tenant_id, pipelineId], enabled: !!member, queryFn: () => getCrmSnapshot(pipelineId || undefined) });
  const clients = useQuery({ queryKey: ['refs-clients'], queryFn: listClientsRef }); const works = useQuery({ queryKey: ['refs-works', leadForm?.client_id], queryFn: () => listWorksRef(leadForm?.client_id || undefined) });
  const data = crm.data; const activities = useMemo(() => new Map((data?.activities ?? []).map((row) => [row.lead_id, row])), [data?.activities]);
  async function refresh() { await qc.invalidateQueries({ queryKey: ['crm'] }); }
  function edit(lead: CrmLead) { setLeadForm({ id: lead.id, stage_id: lead.stage_id, title: lead.title, company_name: lead.company_name ?? '', contact_name: lead.contact_name ?? '', email: lead.email ?? '', phone: lead.phone ?? '', source: lead.source ?? '', expected_value: String(lead.expected_value), probability: String(lead.probability), client_id: lead.client_id ?? '', work_id: lead.work_id ?? '', owner_member_id: lead.owner_member_id ?? '', next_action_at: toLocal(lead.next_action_at) }); }
  async function saveLead() { if (!leadForm?.title.trim()) return toast('Informe o título da oportunidade.', 'warning'); setBusy(true); try { await saveCrmLead({ ...leadForm, pipeline_id: data?.pipeline_id, expected_value: Number(leadForm.expected_value) || 0, probability: leadForm.probability ? Number(leadForm.probability) : undefined, next_action_at: leadForm.next_action_at || null }); setLeadForm(null); await refresh(); toast('Oportunidade salva.', 'success'); } catch (error) { toast((error as Error).message, 'error'); } finally { setBusy(false); } }
  async function move(lead: CrmLead, stageId: string) { if (lead.stage_id === stageId) return; setBusy(true); try { await moveCrmLead(lead.id, stageId); await refresh(); toast('Etapa atualizada.', 'success'); } catch (error) { toast((error as Error).message, 'error'); } finally { setBusy(false); } }
  async function saveActivity() { if (!activityLead || !activity.subject.trim()) return toast('Informe o assunto da atividade.', 'warning'); setBusy(true); try { await saveCrmActivity({ lead_id: activityLead.id, ...activity, due_at: activity.due_at || null }); setActivityLead(null); setActivity({ activity_type: 'nota', subject: '', detail: '', due_at: '' }); await refresh(); toast('Atividade registrada.', 'success'); } catch (error) { toast((error as Error).message, 'error'); } finally { setBusy(false); } }
  async function convert(lead: CrmLead) { setBusy(true); try { const id = await convertCrmLeadToProposal(lead.id); await refresh(); toast(`Proposta criada: ${id.slice(0, 8)}.`, 'success'); } catch (error) { toast((error as Error).message, 'error'); } finally { setBusy(false); } }
  return <div className="space-y-6">
    <PageHeader kicker="Comercial" title="CRM leve" description="Funil de oportunidades, responsáveis, próximas ações e conversão direta em proposta comercial." />
    {crm.isLoading ? <LoadingState /> : crm.error ? <ErrorState message={(crm.error as Error).message} /> : !data ? <EmptyState /> : <>
      <Card><div className="grid gap-4 p-5 md:grid-cols-[1fr_auto]"><SelectField label="Funil" value={pipelineId || data.pipeline_id} onChange={(e) => setPipelineId(e.target.value)}>{data.pipelines.map((p) => <option key={p.id} value={p.id}>{p.nome}</option>)}</SelectField>{can('crm.gerenciar') ? <div className="flex items-end"><Button onClick={() => setLeadForm(emptyLead(data.stages[0]?.id))}>Nova oportunidade</Button></div> : null}</div></Card>
      <div className="grid gap-3 md:grid-cols-4"><Stat label="Oportunidades abertas" value={data.kpis.open} /><Stat label="Pipeline bruto" value={money(data.kpis.pipeline_value)} /><Stat label="Pipeline ponderado" value={money(data.kpis.weighted_value)} /><Stat label="Próximas ações vencidas" value={data.kpis.overdue_actions} /></div>
      <div className="grid auto-cols-[minmax(285px,1fr)] grid-flow-col gap-4 overflow-x-auto pb-3">{data.stages.map((stage) => {
        const leads = data.leads.filter((lead) => lead.stage_id === stage.id);
        return <Card key={stage.id} className="min-w-[285px] overflow-hidden"><div className="h-1.5" style={{ background: stage.color ?? '#64748b' }} /><CardHeader kicker={`${leads.length} oportunidade(s)`} title={stage.nome} /><div className="grid gap-3 p-4">{leads.length ? leads.map((lead) => { const latest = activities.get(lead.id); const overdue = !!lead.next_action_at && lead.next_action_at < new Date().toISOString(); return <Card key={lead.id} className="p-4"><div className="flex items-start justify-between gap-2"><div><p className="font-black text-slate-950 dark:text-white">{lead.title}</p><p className="mt-1 text-xs text-slate-500">{lead.company_name || lead.contact_name || 'Contato não informado'}</p></div><Pill tone={overdue ? 'bad' : stage.won ? 'good' : stage.lost ? 'bad' : 'info'}>{lead.probability}%</Pill></div><p className="mt-3 text-lg font-black">{money(lead.expected_value)}</p><p className="mt-1 text-xs text-slate-500">Próxima ação: {lead.next_action_at ? dateBr(lead.next_action_at) : 'não definida'}</p>{latest ? <p className="mt-2 rounded-lg bg-slate-50 p-2 text-xs text-slate-600 dark:bg-slate-800 dark:text-slate-300">{latest.activity_type}: {latest.subject}</p> : null}<SelectField label="Etapa" value={lead.stage_id} disabled={!can('crm.gerenciar') || busy} onChange={(e) => void move(lead, e.target.value)}>{data.stages.map((option) => <option key={option.id} value={option.id}>{option.nome}</option>)}</SelectField><div className="mt-3 flex flex-wrap gap-2">{can('crm.gerenciar') ? <><Button variant="secondary" onClick={() => edit(lead)}>Editar</Button><Button variant="ghost" onClick={() => setActivityLead(lead)}>Atividade</Button>{!(lead.metadata?.proposal_id) && !stage.lost ? <Button variant="ghost" disabled={busy} onClick={() => void convert(lead)}>Criar proposta</Button> : null}</> : null}</div></Card>; }) : <p className="text-sm text-slate-500">Nenhuma oportunidade nesta etapa.</p>}</div></Card>;
      })}</div>
    </>}
    <Modal open={!!leadForm} wide title={leadForm?.id ? 'Editar oportunidade' : 'Nova oportunidade'} onClose={() => setLeadForm(null)} footer={<><Button variant="ghost" onClick={() => setLeadForm(null)}>Cancelar</Button><Button disabled={busy} onClick={() => void saveLead()}>{busy ? 'Salvando...' : 'Salvar'}</Button></>}>
      {leadForm && data ? <div className="grid gap-4 md:grid-cols-2"><Field label="Título" required value={leadForm.title} onChange={(e) => setLeadForm({ ...leadForm, title: e.target.value })} /><SelectField label="Etapa" value={leadForm.stage_id} onChange={(e) => setLeadForm({ ...leadForm, stage_id: e.target.value })}>{data.stages.map((s) => <option key={s.id} value={s.id}>{s.nome}</option>)}</SelectField><Field label="Empresa" value={leadForm.company_name} onChange={(e) => setLeadForm({ ...leadForm, company_name: e.target.value })} /><Field label="Contato" value={leadForm.contact_name} onChange={(e) => setLeadForm({ ...leadForm, contact_name: e.target.value })} /><Field label="E-mail" type="email" value={leadForm.email} onChange={(e) => setLeadForm({ ...leadForm, email: e.target.value })} /><Field label="Telefone" value={leadForm.phone} onChange={(e) => setLeadForm({ ...leadForm, phone: e.target.value })} /><Field label="Origem" value={leadForm.source} onChange={(e) => setLeadForm({ ...leadForm, source: e.target.value })} /><Field label="Valor esperado" type="number" min="0" step="0.01" value={leadForm.expected_value} onChange={(e) => setLeadForm({ ...leadForm, expected_value: e.target.value })} /><SelectField label="Cliente existente" value={leadForm.client_id} onChange={(e) => setLeadForm({ ...leadForm, client_id: e.target.value, work_id: '' })}><option value="">Ainda não vinculado</option>{(clients.data ?? []).map((r) => <option key={r.id} value={r.id}>{r.label}</option>)}</SelectField><SelectField label="Obra existente" value={leadForm.work_id} onChange={(e) => setLeadForm({ ...leadForm, work_id: e.target.value })}><option value="">Ainda não vinculada</option>{(works.data ?? []).map((r) => <option key={r.id} value={r.id}>{r.label}</option>)}</SelectField><Field label="Próxima ação" type="datetime-local" value={leadForm.next_action_at} onChange={(e) => setLeadForm({ ...leadForm, next_action_at: e.target.value })} /></div> : null}
    </Modal>
    <Modal open={!!activityLead} title="Registrar atividade" onClose={() => setActivityLead(null)} footer={<><Button variant="ghost" onClick={() => setActivityLead(null)}>Cancelar</Button><Button disabled={busy} onClick={() => void saveActivity()}>Salvar atividade</Button></>}>
      <div className="grid gap-4"><p className="text-sm font-bold">{activityLead?.title}</p><SelectField label="Tipo" value={activity.activity_type} onChange={(e) => setActivity({ ...activity, activity_type: e.target.value })}><option value="nota">Nota</option><option value="ligacao">Ligação</option><option value="email">E-mail</option><option value="reuniao">Reunião</option><option value="tarefa">Tarefa</option></SelectField><Field label="Assunto" required value={activity.subject} onChange={(e) => setActivity({ ...activity, subject: e.target.value })} /><TextArea label="Detalhes" value={activity.detail} onChange={(e) => setActivity({ ...activity, detail: e.target.value })} /><Field label="Prazo / próxima ação" type="datetime-local" value={activity.due_at} onChange={(e) => setActivity({ ...activity, due_at: e.target.value })} /></div>
    </Modal>
  </div>;
}
