import { useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Button } from '../../components/ui/Button';
import { Card, CardHeader } from '../../components/ui/Card';
import { Field, SelectField } from '../../components/ui/Field';
import { PageHeader } from '../../components/ui/PageHeader';
import { EmptyState, ErrorState, LoadingState } from '../../components/ui/State';
import { listStockBalances, listStockMovements, registerStockMovement, saveStockItem, type StockBalance } from '../../lib/api/productEvolution';
import { useToast } from '../../lib/toast';
import { dateBr, MetricCard, money, number, Pill, TableShell, Td, Th } from './product/ProductUi';

const initialItem = { id: '', code: '', nome: '', categoria: 'consumivel', unidade: 'un', saldo_minimo: '0', custo_medio: '0' };
export function InventoryPage() {
  const toast = useToast(); const qc = useQueryClient(); const [item, setItem] = useState(initialItem); const [movement, setMovement] = useState({ stock_item_id: '', tipo: 'entrada', quantidade: '0', unit_cost: '0', data: new Date().toISOString().slice(0, 10), observacao: '' }); const [busy, setBusy] = useState(false);
  const balances = useQuery({ queryKey: ['product', 'stock'], queryFn: listStockBalances });
  const movements = useQuery({ queryKey: ['product', 'stock-movements'], queryFn: () => listStockMovements(200) });
  const rows = balances.data ?? [];
  const totals = useMemo(() => ({ items: rows.length, low: rows.filter((row) => row.abaixo_minimo).length, value: rows.reduce((sum, row) => sum + row.valor_estoque, 0) }), [rows]);
  function edit(row: StockBalance) { setItem({ id: row.stock_item_id, code: row.code, nome: row.nome, categoria: row.categoria, unidade: row.unidade, saldo_minimo: String(row.saldo_minimo), custo_medio: String(row.custo_medio) }); }
  async function run(action: () => Promise<unknown>, message: string) { setBusy(true); try { await action(); await Promise.all([qc.invalidateQueries({ queryKey: ['product', 'stock'] }), qc.invalidateQueries({ queryKey: ['product', 'stock-movements'] })]); toast(message, 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Operação não concluída.', 'error'); } finally { setBusy(false); } }
  return <div className="space-y-6"><PageHeader kicker="Evolução do produto" title="Estoque de insumos" description="Entradas, saídas, ajustes, custo médio, mínimo e alerta de reposição para consumíveis do laboratório." />
    <div className="grid gap-3 md:grid-cols-3"><MetricCard label="Itens" value={totals.items} /><MetricCard label="Abaixo do mínimo" value={totals.low} tone={totals.low ? 'bad' : 'good'} /><MetricCard label="Valor em estoque" value={money(totals.value)} /></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader kicker="Cadastro" title={item.id ? 'Editar item' : 'Novo item'} /><div className="grid gap-4 p-5 md:grid-cols-2"><Field label="Código" value={item.code} onChange={(e) => setItem({ ...item, code: e.target.value })} /><Field label="Nome" value={item.nome} onChange={(e) => setItem({ ...item, nome: e.target.value })} /><Field label="Categoria" value={item.categoria} onChange={(e) => setItem({ ...item, categoria: e.target.value })} /><Field label="Unidade" value={item.unidade} onChange={(e) => setItem({ ...item, unidade: e.target.value })} /><Field label="Saldo mínimo" type="number" step="0.01" value={item.saldo_minimo} onChange={(e) => setItem({ ...item, saldo_minimo: e.target.value })} /><Field label="Custo médio" type="number" step="0.01" value={item.custo_medio} onChange={(e) => setItem({ ...item, custo_medio: e.target.value })} /><div className="md:col-span-2 flex gap-2"><Button disabled={busy} onClick={() => void run(() => saveStockItem({ ...item, saldo_minimo: Number(item.saldo_minimo), custo_medio: Number(item.custo_medio), ativo: true }), 'Item salvo.')}>Salvar item</Button>{item.id ? <Button variant="secondary" onClick={() => setItem(initialItem)}>Cancelar</Button> : null}</div></div></Card>
      <Card><CardHeader kicker="Movimento" title="Entrada, saída ou ajuste" /><div className="grid gap-4 p-5 md:grid-cols-2"><SelectField label="Item" value={movement.stock_item_id} onChange={(e) => setMovement({ ...movement, stock_item_id: e.target.value })}><option value="">Selecione</option>{rows.map((row) => <option key={row.stock_item_id} value={row.stock_item_id}>{row.code} · {row.nome}</option>)}</SelectField><SelectField label="Tipo" value={movement.tipo} onChange={(e) => setMovement({ ...movement, tipo: e.target.value })}><option value="entrada">Entrada</option><option value="saida">Saída</option><option value="ajuste_entrada">Ajuste +</option><option value="ajuste_saida">Ajuste -</option></SelectField><Field label="Quantidade" type="number" step="0.01" value={movement.quantidade} onChange={(e) => setMovement({ ...movement, quantidade: e.target.value })} /><Field label="Custo unitário" type="number" step="0.01" value={movement.unit_cost} onChange={(e) => setMovement({ ...movement, unit_cost: e.target.value })} /><Field label="Data" type="date" value={movement.data} onChange={(e) => setMovement({ ...movement, data: e.target.value })} /><Field label="Observação" value={movement.observacao} onChange={(e) => setMovement({ ...movement, observacao: e.target.value })} /><div className="md:col-span-2"><Button disabled={busy || !movement.stock_item_id} onClick={() => void run(() => registerStockMovement({ ...movement, quantidade: Number(movement.quantidade), unit_cost: Number(movement.unit_cost) }), 'Movimento registrado.')}>Registrar movimento</Button></div></div></Card></div>
    {balances.isLoading ? <LoadingState /> : balances.error ? <ErrorState message={(balances.error as Error).message} /> : !rows.length ? <EmptyState /> : <TableShell><thead><tr><Th>Item</Th><Th>Saldo</Th><Th>Mínimo</Th><Th>Custo médio</Th><Th>Valor</Th><Th>Ações</Th></tr></thead><tbody>{rows.map((row) => <tr key={row.stock_item_id}><Td><b>{row.code} · {row.nome}</b><div className="text-xs text-slate-500">{row.categoria}</div></Td><Td><Pill tone={row.abaixo_minimo ? 'bad' : 'good'}>{number(row.saldo, 2)} {row.unidade}</Pill></Td><Td>{number(row.saldo_minimo, 2)}</Td><Td>{money(row.custo_medio)}</Td><Td>{money(row.valor_estoque)}</Td><Td><Button variant="secondary" onClick={() => edit(row)}>Editar</Button></Td></tr>)}</tbody></TableShell>}
    <Card><CardHeader kicker="Auditoria" title="Movimentos recentes" /><div className="p-5">{movements.isLoading ? <LoadingState /> : movements.error ? <ErrorState message={(movements.error as Error).message} /> : !(movements.data?.length) ? <EmptyState /> : <TableShell><thead><tr><Th>Data</Th><Th>Item</Th><Th>Tipo</Th><Th>Quantidade</Th><Th>Custo</Th></tr></thead><tbody>{movements.data.slice(0, 30).map((row) => <tr key={row.id}><Td>{dateBr(row.data)}</Td><Td>{rows.find((itemRow) => itemRow.stock_item_id === row.stock_item_id)?.nome ?? row.stock_item_id.slice(0, 8)}</Td><Td>{row.tipo}</Td><Td>{number(row.quantidade, 2)}</Td><Td>{row.unit_cost == null ? '-' : money(row.unit_cost)}</Td></tr>)}</tbody></TableShell>}</div></Card>
  </div>;
}
